export const DISPLAY_PRODUCT="DISPLAY_PRODUCT";

export const FETCH_PRODUCT_CATEGORIES_SUCCESS="FETCH_PRODUCT_CATEGORIES_SUCCESS";
export const FETCH_PRODUCT_CATEGORIES_FAILED="FETCH_PRODUCT_CATEGORIES_FAILED";

export const SIGNUP="SIGNUP";
export const SIGNUP_FAILED="SIGNUP_FAILED";

export const LOGIN="LOGIN";
export const FORGET_PASSWORD="FORGET_PASSWORD";
export const LOGOUT="LOGOUT";
export const EDIT_PROFILE="EDIT_PROFILE";

export const CATEGORY_PRODUCT="CATEGORY_PRODUCT";
export const CATEGORY_PRODUCT_FAILED="CATEGORY_PRODUCT_FAILED";

export const ORDERED_PRODUCT="ORDERED_PRODUCT";
export const ORDERED_PRODUCT_FAILED="ORDERED_PRODUCT_FAILED";


