export const DISPLAY_PRODUCT="DISPLAY_PRODUCT";

export const FETCH_PRODUCT_CATEGORIES_SUCCESS="FETCH_PRODUCT_CATEGORIES_SUCCESS";
export const FETCH_PRODUCT_CATEGORIES_FAILED="FETCH_PRODUCT_CATEGORIES_FAILED";

export const SIGNUP="SIGNUP";
export const SIGNUP_FAILED="SIGNUP_FAILED";

export const LOGIN="LOGIN";
export const LOGIN_FAILED="LOGIN_FAILED";
export const FORGET_PASSWORD="FORGET_PASSWORD";
export const FORGET_PASSWORD_FAILED="FORGET_PASSWORD_FAILED";

export const LOGOUT="LOGOUT";

export const GET_SINGLE_USER="GET_SINGLE_USER";
export const GET_SINGLE_USER_FAILED="GET_SINGLE_USER_FAILED";
export const EDIT_PROFILE="EDIT_PROFILE";
export const EDIT_PROFILE_FAILED="EDIT_PROFILE_FAILED";

export const CHANGE_PASSWORD="CHANGE_PASSWORD";
export const CHANGE_PASSWORD_FAILED="CHANGE_PASSWORD_FAILED";

export const CATEGORY_PRODUCT="CATEGORY_PRODUCT";
export const CATEGORY_PRODUCT_FAILED="CATEGORY_PRODUCT_FAILED";

export const ORDERED_PRODUCT="ORDERED_PRODUCT";
export const ORDERED_PRODUCT_FAILED="ORDERED_PRODUCT_FAILED";

export const VIEW_ORDER="VIEW_ORDER";
export const VIEW_ORDER_FAILED="VIEW_ORDER_FAILED";

