export const INIT_FETCH_PRODUCT_CATEGORIES = "INIT_FETCH_PRODUCT_CATEGORIES"

export const ADD_PRODUCT_CATEGORIES = "FETCH_PRODUCT_CATEGORIES"
export const REMOVE_PRODUCT_CATEGORIES = 'REMOVE_PRODUCT_CATEGORIES';
export const SINGLE_PRODUCT_CATEGORIES = 'SINGLE_PRODUCT_CATEGORIES';
export const UPDATE_PRODUCT_CATEGORIES = 'UPDATE_PRODUCT_CATEGORIES';


export const FETCH_PRODUCT_CATEGORIES_SUCCESS = "FETCH_PRODUCT_CATEGORIES_SUCCESS"
export const FETCH_PRODUCT_CATEGORIES_FAILED = "FETCH_PRODUCT_CATEGORIES_FAILED"

// init_fetch
// fecth_suceess