export const INIT_FETCH_PRODUCT_CATEGORIES = "INIT_FETCH_PRODUCT_CATEGORIES";
export const INIT_ADD_PRODUCT_CATEGORIES = "INIT_ADD_PRODUCT_CATEGORIES";
export const INIT_UPDATE_PRODUCT_CATEGORIES = "INIT_UPDATE_PRODUCT_CATEGORIES";
export const INIT_REMOVE_PRODUCT_CATEGORIES = "INIT_REMOVE_PRODUCT_CATEGORIES";
export const INIT_SINGLE_PRODUCT_CATEGORIES = "INIT_SINGLE_PRODUCT_CATEGORIES";
export const INIT_FETCH_ORDERS = "INIT_FETCH_ORDERS";
export const INIT_FETCH_ORDERS_DETAILS = "INIT_FETCH_ORDERS_DETAILS";
export const INIT_UPDATE_ORDERS = "INIT_UPDATE_ORDERS";

export const FETCH_PRODUCT_CATEGORIES_SUCCESS = "FETCH_PRODUCT_CATEGORIES_SUCCESS";
export const FETCH_PRODUCT_CATEGORIES_FAILED = "FETCH_PRODUCT_CATEGORIES_FAILED";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";
export const FETCH_ORDERS_DETAILS_SUCCESS = "FETCH_ORDERS_DETAILS_SUCCESS";
export const FETCH_ORDERS_DETAILS_FAILED = "FETCH_ORDERS_DETAILS_FAILED";
export const FETCH_SINGLE_CATEGORIES_SUCCESS = "FETCH_SINGLE_CATEGORIES_SUCCESS";
export const FETCH_SINGLE_CATEGORIES_FAILED = "FETCH_SINGLE_CATEGORIES_FAILED";

export const ADD_PRODUCT_CATEGORIES_SUCCESS = "ADD_PRODUCT_CATEGORIES_SUCCESS";
export const ADD_PRODUCT_CATEGORIES_FAILED = "ADD_PRODUCT_CATEGORIES_FAILED";

export const UPDATE_PRODUCT_CATEGORIES_SUCCESS = "UPDATE_PRODUCT_CATEGORIES_SUCCESS";
export const UPDATE_PRODUCT_CATEGORIES_FAILED = "UPDATE_PRODUCT_CATEGORIES_FAILED";

export const UPDATE_ORDERS_SUCCESS = "UPDATE_ORDERS_SUCCESS";
export const UPDATE_ORDERS_FAILED = "UPDATE_ORDERS_FAILED";

export const REMOVE_PRODUCT_CATEGORIES_SUCCESS = "REMOVE_PRODUCT_CATEGORIES_SUCCESS";
export const REMOVE_PRODUCT_CATEGORIES_FAILED = "REMOVE_PRODUCT_CATEGORIES_FAILED";


// No Use
export const ADD_PRODUCT_CATEGORIES = "FETCH_PRODUCT_CATEGORIES";
export const REMOVE_PRODUCT_CATEGORIES = 'REMOVE_PRODUCT_CATEGORIES';
export const SINGLE_PRODUCT_CATEGORIES = 'SINGLE_PRODUCT_CATEGORIES';
export const UPDATE_PRODUCT_CATEGORIES = 'UPDATE_PRODUCT_CATEGORIES';
export const ADD_ORDERS = "FETCH_ORDERS";
export const UPDATE_ORDERS = 'UPDATE_ORDERS';

// init_fetch
// fecth_suceess