export const INIT_FETCH_PRODUCT_CATEGORIES = "INIT_FETCH_PRODUCT_CATEGORIES";
export const INIT_ADD_PRODUCT_CATEGORIES = "INIT_ADD_PRODUCT_CATEGORIES";
export const INIT_UPDATE_PRODUCT_CATEGORIES = "INIT_UPDATE_PRODUCT_CATEGORIES";
export const INIT_REMOVE_PRODUCT_CATEGORIES = "INIT_REMOVE_PRODUCT_CATEGORIES";
export const INIT_SINGLE_PRODUCT_CATEGORIES = "INIT_SINGLE_PRODUCT_CATEGORIES";
export const INIT_FETCH_ORDERS = "INIT_FETCH_ORDERS";
export const INIT_FETCH_ORDERS_DETAILS = "INIT_FETCH_ORDERS_DETAILS";
export const INIT_UPDATE_ORDERS = "INIT_UPDATE_ORDERS";
export const INIT_TOTAL = "INIT_TOTAL";
export const INIT_PRODUCT_TOTAL = "INIT_PRODUCT_TOTAL";
export const INIT_REVENUE_TOTAL = "INIT_REVENUE_TOTAL";
export const INIT_SEARCH = "INIT_SEARCH";
export const INIT_ORDER_BILL= "INIT_ORDER_BILL";
export const INIT_PARENT_CATEGORY= "INIT_PARENT_CATEGORY";
export const INIT_MONTHLY_PRODUCT= "INIT_MONTHLY_PRODUCT";
export const INIT_REVIEW= "INIT_REVIEW";
export const INIT_DELETE_REVIEW= "INIT_DELETE_REVIEW";

export const FETCH_PRODUCT_CATEGORIES_SUCCESS = "FETCH_PRODUCT_CATEGORIES_SUCCESS";
export const FETCH_PRODUCT_CATEGORIES_FAILED = "FETCH_PRODUCT_CATEGORIES_FAILED";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";
export const FETCH_ORDERS_DETAILS_SUCCESS = "FETCH_ORDERS_DETAILS_SUCCESS";
export const FETCH_ORDERS_DETAILS_FAILED = "FETCH_ORDERS_DETAILS_FAILED";
export const FETCH_SINGLE_CATEGORIES_SUCCESS = "FETCH_SINGLE_CATEGORIES_SUCCESS";
export const FETCH_SINGLE_CATEGORIES_FAILED = "FETCH_SINGLE_CATEGORIES_FAILED";
export const FETCH_TOTAL_SUCCESS = "FETCH_TOTAL_SUCCESS";
export const FETCH_TOTAL_FAILED = "FETCH_TOTAL_FAILED";
export const FETCH_PRODUCT_TOTAL_SUCCESS = "FETCH_PRODUCT_TOTAL_SUCCESS";
export const FETCH_PRODUCT_TOTAL_FAILED = "FETCH_PRODUCT_TOTAL_FAILED";
export const FETCH_REVENUE_TOTAL_SUCCESS = "FETCH_REVENUE_TOTAL_SUCCESS";
export const FETCH_REVENUE_TOTAL_FAILED = "FETCH_REVENUE_TOTAL_FAILED";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";
export const FETCH_SEARCH_FAILED = "FETCH_SEARCH_FAILED";
export const FETCH_ORDER_BILL_SUCCESS = "FETCH_ORDER_BILL_SUCCESS";
export const FETCH_ORDER_BILL_FAILED = "FETCH_ORDER_BILL_FAILED";
export const FETCH_REVIEW_SUCCESS = "FETCH_REVIEW_SUCCESS";
export const FETCH_REVIEW_FAILED = "FETCH_REVIEW_FAILED";
export const FETCH_DELETE_REVIEW_SUCCESS = "FETCH_DELETE_REVIEW_SUCCESS";
export const FETCH_DELETE_REVIEW_FAILED = "FETCH_DELETE_REVIEW_FAILED";

export const FETCH_MONTHLY_PRODUCT_SUCCESS = "FETCH_MONTHLY_PRODUCT_SUCCESS";
export const FETCH_MONTHLY_PRODUCT_FAILED = "FETCH_MONTHLY_PRODUCT_FAILED";

export const FETCH_PARENT_CATEGORY_SUCCESS = "FETCH_PARENT_CATEGORY_SUCCESS";
export const FETCH_PARENT_CATEGORY_FAILED = "FETCH_PARENT_CATEGORY_FAILED";

export const ADD_PRODUCT_CATEGORIES_SUCCESS = "ADD_PRODUCT_CATEGORIES_SUCCESS";
export const ADD_PRODUCT_CATEGORIES_FAILED = "ADD_PRODUCT_CATEGORIES_FAILED";

export const UPDATE_PRODUCT_CATEGORIES_SUCCESS = "UPDATE_PRODUCT_CATEGORIES_SUCCESS";
export const UPDATE_PRODUCT_CATEGORIES_FAILED = "UPDATE_PRODUCT_CATEGORIES_FAILED";

export const UPDATE_ORDERS_SUCCESS = "UPDATE_ORDERS_SUCCESS";
export const UPDATE_ORDERS_FAILED = "UPDATE_ORDERS_FAILED";

export const REMOVE_PRODUCT_CATEGORIES_SUCCESS = "REMOVE_PRODUCT_CATEGORIES_SUCCESS";
export const REMOVE_PRODUCT_CATEGORIES_FAILED = "REMOVE_PRODUCT_CATEGORIES_FAILED";