export const INIT_FETCH_PRODUCTS = "INIT_FETCH_PRODUCTS"
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS"
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED"

export const INIT_ADD_PRODUCT = "INIT_ADD_PRODUCT"
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED"

export const INIT_FETCH_ONE_PRODUCT = "INIT_FETCH_ONE_PRODUCT"
export const FETCH_ONE_PRODUCT_SUCCESS = "FETCH_ONE_PRODUCT_SUCCESS"
export const FETCH_ONE_PRODUCT_FAILED = "FETCH_ONE_PRODUCT_FAILED"

export const INIT_EDIT_PRODUCT = "INIT_EDIT_PRODUCT"
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS"
export const EDIT_PRODUCT_FAILED = "EDIT_PRODUCT_FAILED"

export const INIT_DELETE_PRODUCT_IMAGE = "INIT_DELETE_PRODUCT_IMAGE"
export const DELETE_PRODUCT_IMAGE_SUCCESS = "DELETE_PRODUCT_IMAGE_SUCCESS"
export const DELETE_PRODUCT_IMAGE_FAILED = "DELETE_PRODUCT_IMAGE_FAILED"

export const INIT_DELETE_PRODUCT = "INIT_DELETE_PRODUCT"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED"